### ISSUE TITLE
using params adds quotes @RID in the SQL and seems to cause issues

### ISSUE THREAD

**Issue by Soultripper** [codemix/oriento#184]
Hey

First, thanks for this wrapper. Hoping to be using much more in earnest very soon.

Note, I'm using: Orient 2.0 - M3

I haven't trawled the code but it seems if I do something like:

db.delete('EDGE', 'is_genre').where({out: film.id}).scalar()

which generates valid SQL (DELETE EDGE is_genre WHERE out = "#13:60"), but note that the @RID is wrapped in quotes

never seems to work but executes fine in Studio just copying and pasting it in However, if I do

db.delete('EDGE', 'is_genre).where("out = " + film.id).scalar()

the query executes a-ok as the @RID is not wrapped in quotes e..g

DELETE EDGE is_genre WHERE out = #13:60

I also tried something like

db.delete('EDGE', 'is_genre').where({out: film}).scalar()

and was glad to see it use to @RID but again, it was wrapped in quotes, but it's the same params object as the first so that's not surprising.

This seems counter-intutitive to me if by design, especially if you retrieve the @RID from the object itself.

Can anyone shed light on this? I can go with the solution that's working for now, but would like to know if that's always going to be the way

Many thanks

Sky

**Comment by phpnode** [comment]
@Soultripper RIDs must always be wrapped in RID objects, e.g. `oriento.RID("#12:34"), if you just use the string `"#12:34"` then oriento treats it as a string. This is a necessary evil, without it malicious users could potentially trick the database into revealing confidential information, or cause data corruption.

**Comment by Soultripper** [comment]
Hi

Thanks for getting back.

I understand that, but OrientDB has no problems with RIDs wrapped as a string, certainly, when using the Browse tab in the OrientDB Studio.

That's why I see this as an issue somewhere along the line.

Also, if you extract the RID from the object, why is it then getting wrapped as a string as per the last example?

Thanks

Sky

**Comment by phpnode** [comment]
@Soultripper  It's not about injection attacks specifically, it's about a particularly nasty set of circumstances which can allow attackers to systematically reveal the entire contents of the database. There is an issue open in OrientDB concerning this - https://github.com/orientechnologies/orientdb/issues/2243

> but OrientDB has no problems with RIDs wrapped as a string, certainly, when using the Browse tab in the OrientDB Studio.

OrientDB's REST API suffers from the issue described above and as such is not suitable for use in production. It's really only suitable for use by studio.

> given that it's an RID already . Would it not be better to check if the param value is an RID an wrap it there at the execution of the query?

The issue is that *we cannot safely tell whether a value is a RID or not unless it is an instance of `oriento.RID`*. 

Whenever we retrieve RIDs from the database we automatically wrap them in `oriento.RID` objects, so it's rare for users to care about this detail at all. I saw you [opened another issue](https://github.com/gauravdhiman/sails-orientdb-binary/issues/2) last month which looks related. From that example, you are converting the `RID` to a string. Drop the conversion and your code should work.

**Comment by Soultripper** [comment]
@phpnode 

Ok, so the problem is that value itself of an arbitrary field I am passing in may not be a record Id at all....so I have to  define it explicitly. I can see how that can cause issues. From my viewpoint as a dev, passing anything other then ID property into an ID expected parameter e.g. out: model.name isn't something I would do and therefore thought about. so yes, gotcha...

I guess for my requirement, an .out(@RID) or .in(@RID) would solve this.

so db.delete('EDGE', 'is_genre').out(film) would be lovely

the simple need at mo is to delete all out edges of a vertex for reimport.

I'll give it some more thought. Out of curiosity, have a you real life query where this would be an issue? Trying to think of some in my head, but the query would ultimately fail or be badly written anyway.

e.g. select from Tokens where @rid = (select name from User)

Does Lucas agree with you that the RESP API is not suitable for production? And has there been any feedback from himself on this matter? I see you forked to the OrientDB so I assume you've communicated as he likes dedicated users!

As for the other issue, it was more then just wrapping the @RID from what I recall. Also, I think if the key being passed is ID or @RID it would be perfectly fair to cast the value to an RID.

**Comment by phpnode** [comment]
The following should work:
```js
db.delete('EDGE', 'is_genre').from(film['@rid']).all()
```

> Out of curiosity, have a you real life query where this would be an issue? 

The issue is fairly subtle, but here's one scenario - let's imagine that an application allows input to a certain class like this:
```js
{
  name: "Soultripper",
  active: true,
  foo: "bar"
}
```

If the class is not in strictmode, a user could supply input like this instead:
```js
{
  name: "Soultripper",
  active: true,
  foo: "#5:0"
}
```
Now, the `foo` field looks like an RID, but it's actually a string. If `foo` is a schemaless field, and if Oriento did the magic is-this-string-actually-a-rid? stuff, it would insert a RID here, not a string.

Now, if another part of the application selects this record with a broad `FETCHPLAN`, e.g. `*:1`, it will return the linked record in place of the string the application was expecting. Since it's super rare for apps to validate data coming *out* of the database, this particular scenario would leak the database's admin user (including password). Since RID clusterIds + positions are sequential integers it would be trivial to read the *entire* database this way.

The above is one scenario, there are several others a bit like it.


> Does Luca agree with you that the REST API is not suitable for production? 

You'd have to ask him, it's my personal opinion from having spent quite some time looking into it. I've opened [several issues](https://github.com/orientechnologies/orientdb/issues?q=is%3Aissue+is%3Aopen+REST+author%3Aphpnode) about it but the majority are still open.


> Also, I think if the key being passed is ID or @RID it would be perfectly fair to cast the value to an RID.

`id` wouldn't be safe but `@rid` probably would. Issue is that I don't want to have magic behaviour in just a few places, it's easier to remember "if I need to query by RID I must pass a RID instance" than to remember the edge cases.

**Comment by Soultripper** [comment]
Thanks for the detailed response, and thanks for the example. Was thinking in terms of In and Out...still getting used to various Graph nomenclature.

I do think the example you give, the issue is due to the insert of an incorrect casting of a field which I would strongly agree, that you should not change inserted values unless the schema of that field is known (only escape for security). I was always thinking of a 'where' clause parsing, where it's either ID's or functions / subqueries, but this is where you call it magic behaviour (you must hate RoR!)...I would just call it inconsistent.

Sorry to drag the cat about on this. Just I hope to use OrientDB for some time and your ORM is well written and clearly thought out. My personal conclusion, is that I'm now aware of the issue you've explained, which I am grateful for, where there are known queries that require an ID, a method should be written to allow for an expected ID to be passed and then parsed and ID's allowed, without having to get the develop casting it first. This is affirmed with your to() and from() methods and other ID expecting methods. Since I'm only just starting to get my hands dirty I'm unawares of other calls where this could done, if not done already.

As for the previous issue, it was my own research to modify the code to check for @RID as you say, probably about as safe as it gets. It parses the ID value currently.

Thanks for your patience in this matter.

**Comment by phpnode** [comment]
> btw, Wouldn't FETCHPLAN only go and get that record if was defined as a property in the schema as a link / edge?

But in schemaless mode, that's exactly what you'd be doing:

```sql
create class Wat extends V;
create vertex Wat set name = "hello world";
create vertex Wat set name = #5:0;
select from Wat fetchplan *:1; -- boom!
```

It's way too easy for this to happen by accident, and the result is catastrophic. OrientDB's RIDs are *not* strings and we cannot treat them as such. It really sucks, and I wish this was not the case, because I agree that needing a `RID` class is painful, but there is no way around it. It will be slightly mitigated in future by ES7's "value objects", but for now, we're stuck unfortunately. 


>  I was always thinking of a 'where' clause parsing, where it's either ID's or functions / subqueries, but this is where you call it magic behaviour (you must hate RoR!)...I would just call it inconsistent.

I don't want to introduce inconsistent behaviour, we can't hide the concept of RIDs from the user, they need to know about them to use OrientDB effectively.

**Comment by Soultripper** [comment]
Wow - yep, just ran that example and hello password.

I am now truly convinced this is a flaw in OrientDB designs too.

My thinking is that if you want to use LINKs then I think this should be set as a property in the documents schema, otherwise it is always assumed it's a string field, and never an RID. I think this is perfectly fair to ask of the DBAs due to the security risk as you've discovered.

If you want to have an edge, then the field is distinguished by being prefixed with in_ or out_, therefore a property isn't required (especially for LWE) as fetchplan would be able identify these. (though I'm not 100% on this, just my experience so far)

That way, a fetchplan should only fetch where there's a defined property or has in_ out_ thus avoiding the security issues above. What I am puzzled about is that running a fetchplan, I assume it must run a regexp on all the fields to see if they match as an RID and then fetch that record. That's like a tablescan....just doesn't make sense in terms of performance..query multiple rows, with numerous fields and performance is going to degrade. Indexing which fields to fetch on initial call would surely be a better way. Again, just best guesses as I don't know the internals.

I have posted a question on google groups (strings quacking as RIDs) yesterday about this but nothing back.

Have you posted the exploit example anywhere in groups? 

NB, apologies, I've never used markdown as I'm not normally forum / discussion active..will improve myself and start to use it in future =)
