### ISSUE TITLE
sql batch return issue. 

### ISSUE THREAD

**Issue by martingg88** [codemix/oriento#221]
sql batch "return" doesn't support of return array and json format as documented in orientdb. 

begin
commit [retry <retry>], where:
is the number of retries in case of concurrent modification exception
let <variable> = <SQL>, to assign the result of a SQL command to a variable. To reuse the variable prefix it with the dollar sign $
return , where value can be:
any value. Example: return 3
any variable with $ as prefix. Example: return $a
arrays. Example: return [ $a, $b ]
maps. Example: return { 'first' : $a, 'second' : $b }

**Comment by phpnode** [comment]
@martingg88 please could you clarify this, do you mean that

**A** this should be supported
```js
db
.let('foo', 'SELECT FROM Foo')
.let('bar', 'SELECT FROM Bar')
.return('[$foo, $bar]')
```
(because that should already work)

***or*** do you mean that:

**B** this should be supported
```js
db
.let('foo', 'SELECT FROM Foo')
.let('bar', 'SELECT FROM Bar')
.return(['$foo', '$bar'])
// or
.return({
  foo: '$foo',
  bar: '$bar'
})
```

(because that isn't yet)

***or***, ***C*** do you mean you don't get the expected results back from the server?

Thanks!

**Comment by martingg88** [comment]
yes...B should be supported for oriento library. thanks

**Comment by martingg88** [comment]
thanks
