### ISSUE TITLE
Query results do not match results from studio

### ISSUE THREAD

**Issue by Bandes** [codemix/oriento#257]
I want to select all records returned by shortestPath. So I am using a subquery like so:

SELECT expand(shortestPath) from (SELECT shortestPath(#11:25989,#11:3953,"Both"))

If I run that query directly in studio it returns what I would expect:

    {
    "result": [
        {
            "@type": "d",
            "@rid": "#11:346",
            "@version": 1,
            "@class": "Character",
            "char_id": 2149,
            "in_Enemy": [
                "#14:206",
                "#14:487",
                "#14:1199",
                "#14:1777",

(And a whole bunch more - the full object for each returned node)

But the same query in Oriento via

    db.query('SELECT expand(shortestPath) from (select      shortestPath(#11:346,#11:13138,"Both"))').then(function(path){
    console.log(path);
    return res.json(200, path);
      });

Returns a much smaller and less useful object:

    [{"@rid":"#11:346"},{"@rid":"#11:1045"},{"@rid":"#11:4870"},{"@rid":"#11:13138"}]

What's going on? Is an extra step needed in Oriento?

**Comment by phpnode** [comment]
Hi @Bandes, thanks, this is an unfortunate known issue. The REST and binary APIs return different results in some cases, this is something that will be fixed in forthcoming versions of OrientDB. We're also taking steps to smooth out this differences in the next major version of Oriento, but it will be a while before that is production ready.

In many cases where `expand()` doesn't give you the results you're looking for, you can use a fetchplan instead. In this case:

```js
db
.select('shortestPath(#11:346,#11:13138,"Both")')
.fetch('shortestPath:1')
.column('shortestPath') // optional but will give you an array of results rather than a wrapped object (this is a query builder method, not an orientdb keyword)
.one() // using `one` because the results are wrapped in an object
.then(function (results) {
   console.log(results);
})
```
