### ISSUE TITLE
How can I use transactions?

### ISSUE THREAD

**Issue by StarpTech** [codemix/oriento#259]
Hi, can you make a better example how can I handle transactions with oriento ? Thanks!

````
1. begin
2. commit
3. rollback
````

**Comment by nafetswirth** [comment]
Hello,
i would also like to know how to rollback a transaction.

**Comment by phpnode** [comment]
A transaction is started implicitly whenever you use `.let` at the top level, e.g:
```js
var results = await db
  .let('adminUser', $ => $.select().from('OUser').where({name: 'admin'}))
  .let('newUser', $ => $.insert().into('OUser').set({name: 'Dustin', status: 'active'}))
  .let('knows', $ => $.create('EDGE', 'Knows').from('$adminUser').to('$newUser'))
  .return(['$newUser', '$knows'])
  .commit()
  .all();

console.log(results);
```

Please note that transactions in OrientDB differ from what you might be used to in a traditional RDBMS. There is no concept of rolling back a transaction, because transactions are better described as "a list of commands which will be executed atomically, either they will all pass or they all will fail". This means that "transactions" are prepared before hand by the client, then sent to the server to be executed all at once. 

If you need something more than that, take a look at server side JavaScript: http://www.orientechnologies.com/docs/2.0/orientdb.wiki/Functions.html
