### ISSUE TITLE
Transactions without assignment?

### ISSUE THREAD

**Issue by rschmukler** [codemix/oriento#264]
Is it possible to commit a transaction without an assignment (using `db.let`).

My use case is that I want to import records from a (potentially malformed) CSV. If the CSV is malformed, I want to roll back the transaction. The CSV could have up to 200,000 records. Because of this, the CSV is buffered to be processed 1,000 records at a time.

Currently I am doing the following:

```js
function handleBufferChunk() {
    // convert buffer into records
    for (var i = 0; i < records.length; ++i) {
      tx.let('storeBuffer' + this._bufferCount++, function(db) {
        db.create('vertex', 'MyRecord')
          .set(records[i]);
      });
      buffer = [] // clear buffer
    };
}
```

Ideally I'd be able to fire off a `db.begin()` and a `db.commit()` and go from there. It seems that the API was recently deprecated (I was searching old issues). So I was wondering if this is indeed the way I should be doing it?

Thanks for all your work!

**Comment by phpnode** [comment]
@rschmukler The current query builder is pretty ugly and I'm rewriting it for 2.0 - work in progress [here](https://github.com/codemix/oriento-query-builder). The current query builder doesn't allow it because it is not context aware, it's just a super ugly hack. If you want to do it, you'll have to create a string query and pass it to `db.query(text, {class: 'c'})`. You could still use the query builder to do this as it has a `.toString()` method, just don't forget to put each statement on a new line and start with a `BEGIN`. 

The old `db.begin()` API is deprecated because it's very limited and can only be used in document mode. You can't e.g. create edges or vertices using that API, it doesn't accept SQL, only lists of *document* creates, updates and deletions. This is an orientdb limitation. In the new query builder, `db.begin()` will start a transaction and will support this.

**Comment by ScOut3R** [comment]
I'm commenting here because I'm trying to do a similar batch processing and I'm just trying to get familiar with OrientDB and Oriento. After preparing the transaction with a for loop and using `db.let` how can I commit that because `db.commit` obviously does not work. I've tried to figure it out looking through oriento's source but I'm lost. Would someone be so kind and give me a hint?

Best regards!
