### ISSUE TITLE
Streams

### ISSUE THREAD

**Issue by seeden** [codemix/oriento#290]
Is it possible to use streams somehow?
I am thinking about a big select with thousand of records. It would be nice to get it one by one and not all together. Because the RAM is a bottleneck. Thanks for advice.

**Comment by phpnode** [comment]
Because of the nature of OrientDB's binary protocol - very bad things would happen* if you didn't consume the entire response, so Oriento's transport layer grabs *all* appropriate response data before returning. It might be possible to implement response streams, but it'd be a lot of work.


* the state machine that reads responses would not know when the next response begins, so it would start reading data from offsets that don't match what it's expecting and the server will hang (not crash).

**Comment by seeden** [comment]
Thanks for a very fast answer :+1:
