### ISSUE TITLE
Question: What is best practice for connection management within express.js/wep apps?

### ISSUE THREAD

**Issue by samuelgoldenbaum** [codemix/oriento#326]
Hi guys

Unfortunately, I don't see any info about managing connections within a web application. This is a really an NB topic and need to understand a few things:

Are connections threadsafe? Do we open a connection at app boot up and reuse it through out the app? Do we need to explicitly close connections? 

Any tips and insight greatly appreciated.

**Comment by phpnode** [comment]
The connection pooling feature of Oriento is not recommended and can lead to thread safety issues in OrientDB. If you can, just use one connection, otherwise you may need to create a pool of Oriento db instances at a higher level. So you might e.g. open a database 10x, and have a module which exports a function which returns one of those instances in a round robin.

**Comment by samuelgoldenbaum** [comment]
Are connections threadsafe?

**Comment by phpnode** [comment]
having multiple independent connections is but the way oriento implements connection pooling isn't. I originally wanted to be able to expose one db instance and have it use multiple connections behind the scenes but that isn't possible due to a number of subtle problems. Therefore any pooling needs to take place at a higher level.

**Comment by samuelgoldenbaum** [comment]
Thanks for the reply Charles, obviously this can be quite an issue with high traffic sites

**Comment by flyingrobots** [comment]
For your consideration:

Take advantage of `Promise.using` and disposable connections:

```
var oriento = require('oriento');

// creates a disposable connection to your OrientDB server host
function getServerConnection(opts) {
  return Promise.resolve(oriento(opts))
  .disposer(function(server) {
    return server.close();
  });
}

// creates a disposable connection to your OrientDB database
function getDBConnection(server, opts) {
  return Promise.resolve(server.use(opts))
  .disposer(function(db) {
    return db.close();
  });
}

// sugar method that passes your func a disposable database connection
function usingDB(serverOpts, dbOpts, func) {
  return Promise.using(getServerConnection(serverOpts), function(server) {
    return Promise.using(getDBConnection(server, dbOpts, func);
  });
}
```
Here's an example route that counts the number of `ape` vertices:
```
// NOTE take care to manage the Promise chain properly to avoid disposing database resources before your work has finished.
app.get('/count/apes', function(req, res) {
  usingDB({ /* server options */ }, { /* db options */ }, function(db) {
    return db.select('count(*)').from('ape').scalar()
    .then(function(count) {
      res.json({ apesCount: count });
    });
  });
});
```
This technique has worked really well for me in the past, although I'm not sure how well it scales under heavy traffic. I would be interested to hear what @phpnode has to say about this technique.

**Comment by samuelgoldenbaum** [comment]
Feedback from Orient:

"With node.js in most case the best solution is open a Db at startup, the oriento implementation already manage a pool of connections that are not thread safe, we suggest to open and close a connection per request only in case you want to use record level security."

**Comment by phpnode** [comment]
yes there's quite some overhead in establishing a connection so doing it per request is not practical. It's also not required even for record level security because of auth token support.

**Comment by samuelgoldenbaum** [comment]
I would have thought connection per request would grind the app to a halt.

In a nutshell: in reality, do we need to be concerned about data integrity as connections are not thread safe. If so could you give an example of such a scenario.

And, are we benefiting from connection pooling, be it from oriento in some form, or from orient?

Thanks for the feedback so far

**Comment by phpnode** [comment]
@samuelgoldenbaum uh the issue is quite difficult to explain because it's caused by about 6 different factors that interact subtly. The nature of thread safety issues is that it's very hard to predict the impact, but since this is a database, I'd say it's a pretty bad idea and I've seen OrientDB crashes when testing it several months ago. I *think* now that using auth tokens is supported opting in for those will get around the problem but I've not verified.

You'll get a real boost from using multiple connections because OrientDB's protocol is FIFO, so any long running query will block other queries on the same socket.

**Comment by samuelgoldenbaum** [comment]
Thanks, so in addition to manually managing connections, is there any form of pooling in oriento? Do we need to bother with the config option:
pool: {
 max: 10
}

**Comment by phpnode** [comment]
Just had another look at the code, if you're using auth tokens then you should be ok sticking with oriento level pooling, in which case setting `pool: 10` might be a good idea. If you're *not* using auth tokens then yes you'll need to do your own connection management and you can remove that `pool` config option.

**Comment by samuelgoldenbaum** [comment]
Ok, looking at Index,js, line 56 in binary transport, it does take the pool config into account.

To use the auth token, is it simply:

      useToken: true

In the config. That was all I could see in the tests.
